sudo: false
language: groovy
jdk:
- oraclejdk7
script: "./travis-build.sh"
branches:
  only:
    - master
    - /^[0-9.]+.*$/
before_script:
  - rm -rf target
  - rm -rf docs
env:
  global:
  - GIT_NAME="Brian Saville"
  - GIT_EMAIL="bksaville@gmail.com"
  # travis encrypt -a env.global 'BINTRAY_USER=myusername'
  # travis encrypt -a env.global 'BINTRAY_KEY=mypassword'
  # travis encrypt -a env.global 'GITHUB_TOKEN=token' # get the token from https://github.com/settings/applications
  - secure: dVM+jJNq6YB0o6Fw48aST6oZ7QusSoMoiUBD71/QOW679J1XIQHwaP2RYRqGY5b6A6ub6X7WaSkJ+d569BTL491S7buJxH0+OqSGrduxCxOIkc/9O9eX26WoZtnseKJy2SjclFJaomusLKtvTLrR3nz0SL2sMuAhkCqu0ksbk6o=
  - secure: ZKSGT4j+qrm/kGXIGCq4g8n5oDY7F20mevmA0e+y9/TSutNQZ4rz7f0DYp+I6kH4SZTM0RksSJNff/kFA3hE6VQqINcivU6dOIrVCFH0aWJO3nMo+7y37ZjhtfqkYpVxX5HIUmEINn80yL1aMEcFx2Ji5rc3+v3UVOWPnnlhfjY=
  - secure: JZMnGIywsEIG9s9dPQ3KQlCoqjPYxDXPKEGSAylFpSKmBXPCUnoZsAefFrgnajFJDlXMlV8VL1PSqn//KUOFuSurPym+ZTg0HfNeWs7K50yg3J5465gE9NzDLJBGDJDVa31nuEsI54QdxoJy6pUPA+l9nIJYz3dbBYe03GYpT94=
